scraper:
  feed_url: "https://rss.arxiv.org/rss/cs.CV"
  max_workers: 8
  pdf_lines_start: 2
  pdf_lines_end: 30

whitelists:
  titles:
    - "Few Shot"
    - "Low Light"
    - "MOT"
    - "Multiple Object Tracking"
    - "Nerf"
    - "Open Set"
    - "Remote Sensing"
    - "SAR"
    - "Satellite"
    - "Zero Shot"

  affiliations:
    - "Adobe"
    - "Apple"
    - "Berkeley"
    - "ByteDance"
    - "Caltech"
    - "California Institute of Technology"
    - "Carnegie Mellon University"
    - "CMU"
    - "DeepMind"
    - "Freiburg"
    - "Google"
    - "HKUST"
    - "IDEA-Research"
    - "INRIA"
    - "KAIST"
    - "Michigan"
    - "Microsoft"
    - "MIT"
    - "Meta"
    - "Munich"
    - "Nvidia"
    - "Oxford"
    - "Princeton"
    - "Stanford"
    - "Technion"
    - "Tel-Aviv"
    - "Toronto"
    - "Toyota"
    - "Tsinghua"
    - "Voxel51"
    - "Weizmann"
    - "Yale"
    - "Zurich"

  authors:
    - "Andrew Ng"
    - "Avidan"
    - "Bengio"
    - "Belongie"
    - "Bursuc"
    - "Christian Wolf"
    - "Corso"
    - "Cremers"
    - "Darrell"
    - "Dekel"
    - "Doll√°r"
    - "Farhadi"
    - "Fei-Fei"
    - "Feichtenhofer"
    - "Geiger"
    - "Girshick"
    - "Gkioxari"
    - "Goodfellow"
    - "Grauman"
    - "Guibas"
    - "Hammarstrand"
    - "Hinton"
    - "Ioffe"
    - "Ishan Misra"
    - "Johnson"
    - "Kaiming"
    - "Kanade"
    - "Kirillov"
    - "LeCun"
    - "Leal-Taixe"
    - "Lior Wolf"
    - "Litany"
    - "Malik"
    - "Mubarak Shah"
    - "Pollefeys"
    - "Ramanan"
    - "Savarese"
    - "Scaramuzza"
    - "Schmidhuber"
    - "Sebastian Thrun"
    - "Snavely"
    - "Susskind"
    - "Svensson"
    - "Torralba"
    - "Torr"
    - "Vedaldi"
    - "Zisserman"
